#!/usr/bin/env bash
# configure webserver files
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test syntax errors
sudo nginx -t

# restart config files after change
sudo service nginx restart
