#!/usr/bin/env bash
# bash script to installs Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo service nginx restart
