#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for ((i=1; i<=20; i++)); do
    case $i in
        4)
	    echo "$i"
            echo "bad luck from China"
            ;;
        9)
	    echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
	    echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
done
