#!/usr/bin/env bash
# This script is displaying the content of the current directory
cd "$(dirname "$0")" || exit
for file in *; do
if [ -f "$file" ]; then
name_after_dash=$(echo "$file" | cut -d'-' -f2-)
echo "$name_after_dash"
fi
done
